Repository cyclops-operation/with-pet, pull requests merged in 2023-01, with the labels that each got.

#9 feat(accordion): 아코디언 컴포넌트 추가, 스토리북 추가
  components/Accordion/index.stories.tsx
  components/Accordion/index.tsx
Labels: Feature, Review needed

#11 config(emotion): Add emotion
  next.config.js
  package.json
  pages/_app.page.tsx
  styles/colors/zinc.ts
  styles/default.ts
  styles/emotion.d.ts
  styles/global.ts
  styles/light-theme.ts
  styles/theme.ts
  styles/types.ts
  yarn.lock
Labels: Config

#12 fix: Migrate tailwindcss to styled-components
  .storybook/preview.js
  common/custom-styles.ts
  common/type-utils.ts
  components/Button/index.style.ts
  components/Button/index.tsx
  components/Radio/index.stories.tsx
  components/Radio/index.style.ts
  components/Radio/index.tsx
  components/Select/common/menu.tsx
  components/Select/common/menu/index.style.ts
  components/Select/common/menu/index.tsx
  components/Select/common/option.tsx
  components/Select/common/option/index.style.ts
  components/Select/common/option/index.tsx
  components/Select/common/trigger/index.style.ts
  components/Select/common/trigger/index.tsx
  package.json
  pages/home/src/ui/button-group/index.style.ts
  pages/home/src/ui/button-group/index.tsx
  pages/home/src/ui/header-text/index.style.ts
  pages/home/src/ui/header-text/index.tsx
  styles/colors/zinc.ts
  styles/dark-theme.ts
  styles/default.ts
  styles/focus-ring.ts
  styles/light-theme.ts
  styles/theme.ts
  styles/types.ts
  styles/utils.ts
  tailwind.config.js
Labels: Feature, Review needed

#13 feat(input): styled 마이그레이션
  components/Input/common/hint-text.tsx
  components/Input/common/hint-text/index.style.ts
  components/Input/common/hint-text/index.tsx
  components/Input/common/input.tsx
  components/Input/common/input/index.style.ts
  components/Input/common/input/index.tsx
  components/Input/common/label/index.style.ts
  components/Input/common/label/index.tsx
  components/Input/input-box.tsx
  styles/colors/red.ts
  styles/colors/sky.ts
  styles/dark-theme.ts
  styles/light-theme.ts
Labels: Feature, Refactor, Review needed

#14 feat: 유기동물 찾기 페이지 추가
  common/types.ts
  components/Button/index.stories.tsx
  components/Button/index.style.ts
  components/Button/text-button/index.stories.tsx
  components/Button/text-button/index.style.ts
  components/Button/text-button/index.tsx
  components/Select/common/menu/index.tsx
  components/Select/common/trigger/index.style.ts
  components/Select/common/trigger/index.tsx
  components/Select/index.stories.tsx
  components/Select/index.style.ts
  components/Select/index.tsx
  components/combobox/common/trigger/index.style.ts
  components/combobox/common/trigger/index.tsx
  components/combobox/index.style.ts
  components/combobox/index.tsx
  components/combobox/use-combobox.ts
  components/icon/index.style.ts
  components/icon/index.tsx
  components/menu/index.style.ts
  components/menu/index.tsx
  components/option/index.style.ts
  components/option/index.tsx
  pages/_document.page.tsx
  pages/find/index.page.tsx
  pages/find/index.style.ts
  pages/find/src/ui/find-form/index.style.ts
  pages/find/src/ui/find-form/index.tsx
  pages/find/src/ui/header.tsx
  pages/find/src/ui/modules/form-combobox/index.style.ts
  pages/find/src/ui/modules/form-combobox/index.tsx
  pages/find/src/ui/navigation.tsx
  pages/home/index.page.tsx
  pages/home/index.style.ts
  pages/home/src/ui/button-group/index.style.ts
  pages/src/ui/Layout/index.style.ts
  pages/src/ui/Layout/index.tsx
Labels: Feature, Merge needed
